### ISSUE TITLE
POST to route returns 404

### ISSUE THREAD

**Issue by AllSpeeds** [panthershark/pipeline-router#10]
GIVEN route table:

```
"router": {
        "options": {
          "routes": {
            "someGetRoute": {
              "method": "GET",
              "name": "someGetRoute",
              "path": "/someGetRoute",
              "description": "Example GET route",
              "handler": "someGetRoute",
              "params": {},
              "enabled": true
            },
            "somePostRoute": {
              "method": "POST",
              "name": "somePostRoute",
              "path": "/somePostRoute",
              "description": "Example POST route",
              "handler": "somePostRoute",
              "params": {},
              "enabled": true
            }
}
}
}
```

WHEN looping over routes looking for a match
AND when matched
AND when method matches
THEN move on

Currently, this code (https://github.com/tommymessbauer/pipeline-router/blob/master/index.js#L123):

```
    // quick fail check
    if (matched || httpContext.request.method !== options.method) {
      next();
    }
```

will not find a match OR the method will not match and fire next() and end with match undefined which returns a 404 as the POST response:

```
this.plRouter.on('end', function(err, results) {
    var matched = results[0].matched,
        res = results[0].httpContext.response;

    that.emit('end', err, results);

    if ((!matched || err) && res) {
      res.statusCode = 404;
      res.write("No matching route or failed route");
      res.end(err ? err.stack : '');
    }
  });
```

**Comment by AllSpeeds** [comment]
Forked, writing a test with a route table and going to submit a PR.

**Comment by panthershark** [comment]
Route tables are part of https://github.com/mixdown/router, not pipeline-router.

**Comment by panthershark** [comment]
next() does not end the pipeline.  It tells the pipeline to try the next step.

**Comment by AllSpeeds** [comment]
@tommymessbauer You're right, next() does not necessarily end the pipeline.  You're also right about the route table, however are you saying the fix for this is in mixdown-router?  The code path still breaks.

**Comment by panthershark** [comment]
I am just saying that you cannot initialize a pipeline router with a route table.  Mixdown-router uses a route table.

**Comment by AllSpeeds** [comment]
yeah and you said it 6 times....I get it.

**Comment by panthershark** [comment]
I promise that was a github bug. I pressed "Comment" and it did nothing. So it took 6 tries before I realized that the page was not updating correctly.
