### ISSUE TITLE
post routes aren't parsing form body correctly

### ISSUE THREAD

**Issue by cappslock** [panthershark/pipeline-router#4]
I have a simple HTML form with two inputs posting to a route. When intercepting the route on a POST request, the body only contains the first input.

Additionally, the parsed input is an array instead of a string even though there is only one item.

**Comment by panthershark** [comment]
Send me an example of a body that is not parsing and I'll put it in a test.

**Comment by panthershark** [comment]
Looks like a formaline processing flow issue. Should have fix tonight.

**Comment by panthershark** [comment]
Fixed and published to 0.6.0.  Migrated to formidable instead of formaline.  Added unit test.
